name: Lint and test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies ☕️
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint 🔍
        run: flake8 jsonrpyc.py setup.py tests

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies ☕️
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Check bundling 📦
        run: python setup.py sdist

      - name: Check setup 🚦
        run: twine check "dist/$( python setup.py --fullname ).tar.gz"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["27", "37", "38", "39"]
    name: test (python ${{ matrix.python }})
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Pull docker image 🐳
        run: docker pull riga/law:py${{ matrix.python }}

      - name: Test 🎢
        run: docker run --rm -t -v $( pwd ):/jsonrpyc -w /jsonrpyc riga/py-base:{{ matrix.python }} python -m unittest tests
